name: CD - Deploy to Azure

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Docker image to deploy
        run: |
          echo "IMAGE_TO_DEPLOY=${{ github.event.client_payload.image }}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "myappfirst"               
          images: ${{ env.IMAGE_TO_DEPLOY }}  
