name: Build and Push Docker image to ACR

on:
  push:
    branches:
      - Dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.AZURE_CONTAINER_REGISTRY }}/hello-node:${{ github.ref_name }}
          docker build -t $IMAGE_NAME .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME

      - name: Trigger CD pipeline
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy
          client-payload: '{"image":"${{ env.IMAGE_NAME }}"}'

       
